### ISSUE TITLE
[REQUEST] Youtube, Rocketleague, Sound 

### ISSUE THREAD

**Issue by ksbox** [GeekTekRob/GTR_Streamdeck_Icons#3]
**What would you like to be added?**
Your game icons are so good! Could you add a Rocketleague one as well?

Youtube icon would be good too.

I'm also looking for a sound icon. I see your microphone ones so I think an audio icon for mute and unmuted would be good too.

**Comment by GeekTekRob** [comment]
I redid all the icons without the frames.  Sorry for some reason it didn't notify me someone put the issue in.  I will add the Rocket league and Youtube in the archived Framed version also though.

**Comment by GeekTekRob** [comment]
This was placed in the latest release in the FRAMED folders, or can pull icon packs from the TouchPortal folders.

**Comment by ksbox** [comment]
its so good! thank you!
